accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp import views
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns =[
    path('hello_world/',views.hello_world,name='hello_world'),
    path('login/',LoginView.as_view(template_name="accountapp/login.html"), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),

    path('create/',AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>',AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>',AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>',AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name ='articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(),name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accountapp.urls')),
    path('profiles/',include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family:'NanumSquareR';">
    {% include 'header.html' %}
    <hr>

    {% block content %}
    {% endblock %}

    <hr>
    {% include 'footer.html' %}

</body>

</html>

templates/footer.html
<div class="pragmatic_footer">
    <div class="pragmatic_footer_button">
        <span>공지사항</span>
        <span>제휴사항</span>
        <span>회사소개</span>
    </div>
    <div style="margin-top:1rem;">
        <h6 class="pragmatic_logo">Pragmatic</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">

    <title>Pragmatic</title>
    <!-- BOOTSTRAP LINK   -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Google Font LINK   -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Song+Myung&display=swap" rel="stylesheet">

    <!--   DEFAULT CSS LINK     -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <!-- Naver Font   -->
    <style>
        @font-face {
            font-family: 'NanumSquareB';
            src:local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.ttf' %}" format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src:local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.ttf' %}" format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src:local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.ttf' %}" format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareR';
            src:local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.ttf' %}" format("opentype");
        }
    </style>
</head>

templates/header.html
<div class="pragmatic_header">
    <div>
        <h1 class="pragmatic_logo">Pragmatic</h1>
    </div>
    <div>
        <a href="{% url 'articleapp:list' %}">
            <span>게시판</span>
        </a>
        <span>nav2</span>
        <span>nav3</span>
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
            <span>로그인</span>
        </a>
        <a href="{% url 'accountapp:create' %}">
            <span>회원가입</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}">
            <span>마이페이지</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
            <span>로그아웃</span>
        </a>
        {% endif %}

    </div>
</div>